service: simple-lambda

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'


  
  

